# Generated by Django 4.2.2 on 2023-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descriptions',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
