# Generated by Django 4.2.2 on 2023-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
